#!/usr/bin/env bash

if
  [[ -s "/home/sec/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/environment" ]]
then
  source "/home/sec/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/environment"
  exec rdoc "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/sec/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/environment'" >&2
  exit 1
fi
